# Generated by Django 4.2 on 2023-05-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='email',
            field=models.EmailField(db_column='email', default=None, max_length=254, null=True),
        ),
    ]
